### PR TITLE
Improve dump, improve BCI2Line conversion

### PR DESCRIPTION
**Pull request by nitsanw**
minor fixes, added info on errors in the dump. The err histogram should be made part of default reports IMO.

### CODE REVIEW

**Comment by RichardWarburton** [comment]
Can you confirm that the code that you've marked as being the same algorithm as hprof is your code and not copied from hprof?

Assuming its from hprof, then if hprof is Apache licensed then its fine, but if hprof is GPL licensed then its an issue because makes the whole of honest profiler GPL and stops other people linking against and integrating honest profiler. Even if it is Apache licensed the copyright notice should be retained for that blob of code.

**Comment by nitsanw** [comment]
I took the original code and modified the naming/interaction with JVMTI etc. It's a trivial algorithm extracted from sample code so not sure where it stands from legal viewpoint.
The file(hprof_util.c) includes the following header:
     
    /*
     * Copyright (c) 2003, 2011, Oracle and/or its affiliates. All rights reserved.
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     *   - Redistributions of source code must retain the above copyright
     *     notice, this list of conditions and the following disclaimer.
     *
     *   - Redistributions in binary form must reproduce the above copyright
     *     notice, this list of conditions and the following disclaimer in the
     *     documentation and/or other materials provided with the distribution.
     *
     *   - Neither the name of Oracle nor the names of its
     *     contributors may be used to endorse or promote products derived
     *     from this software without specific prior written permission.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
     * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
     * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
     * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
     * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
     * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
     * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
     * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
     * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
     * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
     * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     */
The relevant methods are:

    map_loc2line(jlocation location, jvmtiLineNumberEntry *table, jint count)
    jvmtiDeallocate(void* p)

**Comment by RichardWarburton** [comment]
That's the 3-clause BSD license, so its fine to include but the file does need Oracle's copyright notice at the top.

**Comment by RichardWarburton** [comment]
Not the whole license, just `Copyright (c) 2003, 2011, Oracle and/or its affiliates.`

**Comment by nitsanw** [comment]
Last commit should resolve doubts I believe, up to you.

**Comment by RichardWarburton** [comment]
Thanks.

**Pull request merged**
