### PR TITLE
Added collection of native thread id of sampled process. 

### PR DESCRIPTION
**Pull request by lifey**
This do not handle writing it to file yet. However I want to know what you think about the direction

### CODE REVIEW

**Comment by RichardWarburton** [comment]
This PR is related to #73

**Comment by nitsanw** [comment]
This is not going to be OK:
http://stackoverflow.com/questions/9096544/what-is-impact-if-i-call-syscallsys-gettid-from-signal-handler
getid is not safe for async code.

**Comment by RichardWarburton** [comment]
Yeah, my apologies for not making it clearer. I spoke with @lifey by email about this PR and explained that the approach wasn't viable. I should probably just close the PR. Thanks for the offer, but I probably need to be careful about accepting PRs in general!

**Comment by lifey** [comment]
Indeed we discussed this back then. Wonder if there is a safe approach to do the same,

**Pull request closed without merging**
